<a href="https://colab.research.google.com/github/KavyaM22/Sentimental-Analysis/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# DATA PREPROCESSING
import numpy as np
import pandas as pd
data=pd.read_csv("/content/Restaurant reviews (1).csv")
data.head()

,Restaurant,Reviewer,Review,Rating,Metadata,Time,Pictures
0,Beyond Flavours,Rusha Chakraborty,"The ambience was good, food was quite good . h...",5,"1 Review , 2 Followers",5/25/2019 15:54,0
1,Beyond Flavours,Anusha Tirumalaneedi,Ambience is too good for a pleasant evening. S...,5,"3 Reviews , 2 Followers",5/25/2019 14:20,0
2,Beyond Flavours,Ashok Shekhawat,A must try.. great food great ambience. Thnx f...,5,"2 Reviews , 3 Followers",5/24/2019 22:54,0
3,Beyond Flavours,Swapnil Sarkar,Soumen das and Arun was a great guy. Only beca...,5,"1 Review , 1 Follower",5/24/2019 22:11,0
4,Beyond Flavours,Dileep,Food is good.we ordered Kodi drumsticks and ba...,5,"3 Reviews , 2 Followers",5/24/2019 21:37,0

In [ ]:
shape = data.shape

print(f'The dataset has {shape[0]} rows and {shape[1]} columns.')

The dataset has 10000 rows and 7 columns.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Restaurant  10000 non-null  object
 1   Reviewer    9962 non-null   object
 2   Review      9955 non-null   object
 3   Rating      9962 non-null   object
 4   Metadata    9962 non-null   object
 5   Time        9962 non-null   object
 6   Pictures    10000 non-null  int64
dtypes: int64(1), object(6)
memory usage: 547.0+ KB

In [ ]:
data.describe()

           Pictures
count  10000.000000
mean       0.748600
std        2.570381
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max       64.000000

In [ ]:
#Check for missing values
print(data.isnull().sum())

Restaurant     0
Reviewer      38
Review        45
Rating        38
Metadata      38
Time          38
Pictures       0
dtype: int64
(10000, 7)

In [ ]:
# Fill missing values in 'Reviewer', 'Review', 'Rating', 'Metadata', and 'Time' columns with a placeholder
placeholder = 'Unknown'
data['Reviewer'].fillna(placeholder, inplace=True)
data['Review'].fillna(placeholder, inplace=True)
data['Rating'].fillna(placeholder, inplace=True)
data['Metadata'].fillna(placeholder, inplace=True)
data['Time'].fillna(placeholder, inplace=True)

In [ ]:
# Fill missing values in 'Reviewer', 'Review', 'Rating', 'Metadata', and 'Time' columns
import pandas as pd
from tqdm import tqdm

tqdm.pandas()



# Impute missing values
text_columns = ['Restaurant', 'Reviewer', 'Review', 'Metadata', 'Time']
numeric_columns = ['Rating', 'Pictures']

data[text_columns] = data[text_columns].fillna('Missing')
data[numeric_columns] = data[numeric_columns].fillna(-1)

# Display the head of the dataframe to confirm changes
print(data.head())

(10000, 7)

In [ ]:
# Convert 'Rating' column to numeric, coerce errors to  and then fill  with a placeholder value
# Assuming ratings are on a scale of 1-5
#errors='coerce': This parameter specifies that any values that cannot be converted to numeric types should be set to NaN (missing values).
#This is useful for handling cases where the 'Rating' column may contain non-numeric values or strings that cannot be converted to numbers.
data['Rating'] = pd.to_numeric(data['Rating'], errors='coerce').fillna(-1).astype(int)
print(data['Rating'])

0       5
1       5
2       5
3       5
4       5
       ..
9995    3
9996    4
9997    1
9998    4
9999    3
Name: Rating, Length: 10000, dtype: int64

In [ ]:
print(data['Time'])

0       5/25/2019 15:54
1       5/25/2019 14:20
2       5/24/2019 22:54
3       5/24/2019 22:11
4       5/24/2019 21:37
             ...
9995      6/5/2016 0:08
9996     6/4/2016 22:01
9997     6/3/2016 10:37
9998    5/31/2016 17:22
9999    5/31/2016 16:41
Name: Time, Length: 10000, dtype: object

In [ ]:
# Convert 'Time' column to datetime
data['Time'] = pd.to_datetime(data['Time'], errors='coerce')
print(data['Time'])

0      2019-05-25 15:54:00
1      2019-05-25 14:20:00
2      2019-05-24 22:54:00
3      2019-05-24 22:11:00
4      2019-05-24 21:37:00
               ...
9995   2016-06-05 00:08:00
9996   2016-06-04 22:01:00
9997   2016-06-03 10:37:00
9998   2016-05-31 17:22:00
9999   2016-05-31 16:41:00
Name: Time, Length: 10000, dtype: datetime64[ns]

In [ ]:
# Remove duplicate rows
initial_row_count = data.shape[0]
data.drop_duplicates(inplace=True)
final_row_count = data.shape[0]
print(initial_row_count)
print(final_row_count )

10000
9964

In [ ]:
# Standardize text data by trimming whitespace and converting to lowercase
text_columns = ['Restaurant', 'Reviewer', 'Review', 'Metadata']
for col in text_columns:
    data[col] = data[col].str.strip().str.lower()

print(data[col])
data.head()

0             1 review , 2 followers
1            3 reviews , 2 followers
2            2 reviews , 3 followers
3              1 review , 1 follower
4            3 reviews , 2 followers
                    ...
9995       53 reviews , 54 followers
9996        2 reviews , 53 followers
9997      65 reviews , 423 followers
9998      13 reviews , 144 followers
9999    472 reviews , 1302 followers
Name: Metadata, Length: 9964, dtype: object

,Restaurant,Reviewer,Review,Rating,Metadata,Time,Pictures
0,beyond flavours,rusha chakraborty,"the ambience was good, food was quite good . h...",5,"1 review , 2 followers",2019-05-25 15:54:00,0
1,beyond flavours,anusha tirumalaneedi,ambience is too good for a pleasant evening. s...,5,"3 reviews , 2 followers",2019-05-25 14:20:00,0
2,beyond flavours,ashok shekhawat,a must try.. great food great ambience. thnx f...,5,"2 reviews , 3 followers",2019-05-24 22:54:00,0
3,beyond flavours,swapnil sarkar,soumen das and arun was a great guy. only beca...,5,"1 review , 1 follower",2019-05-24 22:11:00,0
4,beyond flavours,dileep,food is good.we ordered kodi drumsticks and ba...,5,"3 reviews , 2 followers",2019-05-24 21:37:00,0

In [ ]:
print('Duplicates removed and text data standardized.')
print('Rows removed:', initial_row_count - final_row_count)

Duplicates removed and text data standardized.
Rows removed: 36

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

# Save the training and testing sets to CSV files
train_data.to_csv('train_reviews.csv', index=False)
test_data.to_csv('test_reviews.csv', index=False)
print(train_data)

                                 Restaurant         Reviewer  \
8140                               delhi-39     akash bhagat
2375                                   amul           sameer
6794  yum yum tree - the arabian food court    karthik nelli
4439             la la land - bar & kitchen     asha bishnoi
6195                   prism club & kitchen         t jyothi
...                                     ...              ...
5734                           being hungry   raviraj bharti
5191              hitech bawarchi food zone           ramana
5390                        diners pavilion  hemanth sriteja
860                             hyper local       himakar yv
7270                                labonel     piyush bajaj

                                                 Review  Rating  \
8140  food could have been more tasty..nd quality to...       2
2375                                          excellent       5
6794  been here for dinner with team. place was full...       4
4439  la la land is best place for those who love da...       4
6195  i would say this was one of the best clubs i h...       5
...                                                 ...     ...
5734                                very less quantity.       2
5191                                               good       5
5390  chicken laila biryani and spicy chicken table ...       4
860   they have this amazing ipl offer\n600 for 4 pi...       3
7270  absolute bliss to have a brownie or cake from ...       5

                        Metadata                Time  Pictures
8140       1 review , 1 follower 2018-06-17 15:01:00         0
2375                   0 reviews 2018-07-27 18:14:00         0
6794   14 reviews , 77 followers 2018-07-07 11:33:00         3
4439   19 reviews , 10 followers 2019-01-12 23:38:00         0
6195       1 review , 1 follower 2019-01-26 11:27:00         0
...                          ...                 ...       ...
5734                    1 review 2018-09-07 22:18:00         0
5191                   0 reviews 2018-07-29 13:08:00         0
5390      4 reviews , 1 follower 2018-06-23 16:20:00         0
860   49 reviews , 284 followers 2019-04-07 03:22:00         1
7270   8 reviews , 280 followers 2017-03-24 16:26:00         0

[7971 rows x 7 columns]

In [ ]:
print(test_data)

                  Restaurant           Reviewer  \
5229       biryanis and more      praveen kumar
9903        chinese pavilion        arun prasad
6176    prism club & kitchen    avinash a naidu
7541  royal spicy restaurant        ashima jena
1208       absolute sizzlers          jagan jrb
...                      ...                ...
1287       absolute sizzlers    ʀʌtʜoʀ sɩŋʛʜ rt
2069                13 dhaba  taranddeep singgh
6319            dine o china       harika reddy
4102          karachi bakery            bhumika
6037              pourhouse7     nikhil agarwal

                                                 Review  Rating  \
5229  good place to dine with family and friends. th...       5
9903  overrated place. it's a disappointment and bel...       2
6176  one of the best place in hyderabad .gud servic...       4
7541  ordered noodles and received without a fork......       2
1208  i went here earlier some time back and was rea...       1
...                                                 ...     ...
1287  i ever feel bad at this place such a honor tre...       5
2069  the food was prepared quickly and was also del...       3
6319  this restaurant located in the same complex of...       2
4102  we are new to hyderabad and ordered a chocolat...       4
6037  we went with a lot of hopes, but were disappoi...       1

                        Metadata                Time  Pictures
5229     3 reviews , 8 followers 2018-12-27 15:19:00         0
9903    5 reviews , 41 followers 2019-04-28 20:37:00         0
6176  21 reviews , 178 followers 2019-02-14 17:27:00         0
7541                    1 review 2018-08-14 04:45:00         0
1208    5 reviews , 50 followers 2019-05-17 16:29:00         0
...                          ...                 ...       ...
1287                   2 reviews 2019-03-03 19:31:00         0
2069                    1 review 2018-09-29 20:57:00         0
6319   15 reviews , 24 followers 2019-01-19 23:23:00         3
4102   65 reviews , 12 followers 2019-04-30 12:42:00         1
6037     3 reviews , 4 followers 2019-04-07 14:21:00         0

[1993 rows x 7 columns]

In [ ]:
print("Training and testing sets have been created and saved as 'train_reviews.csv' and 'test_reviews.csv'.")

Training and testing sets have been created and saved as 'train_reviews.csv' and 'test_reviews.csv'.